# Generated by Django 5.2.15 on 2026-07-17 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_source'),
        ('taxonomy', '0005_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('entry_on', models.DateTimeField(auto_now_add=True, db_column='entry_on')),
                ('updated_on', models.DateTimeField(auto_now=True, db_column='updated_on')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Short summary shown in listings/previews', null=True)),
                ('content', models.TextField(help_text='Full rich HTML article content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/featured/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_breaking_news', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_editors_pick', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveIntegerField(default=1)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=150, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='articles/og/')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='articles/twitter/')),
                ('authors', models.ManyToManyField(blank=True, related_name='articles', to='articles.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='taxonomy.categories')),
                ('entry_by', models.ForeignKey(blank=True, db_column='entry_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_articles', models.ManyToManyField(blank=True, to='articles.article')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.source')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='taxonomy.tags')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ARTICLES',
                'ordering': ['-publish_date', '-entry_on'],
            },
        ),
    ]
