# Generated by Django 5.2.15 on 2026-07-15 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='CATEGORIES',
        ),
    ]
