# Generated by Django 5.2.15 on 2026-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_alter_categories_entry_by_alter_categories_entry_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='image',
        ),
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: fa-folder-open', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='icon_color',
            field=models.CharField(default='text-textsecondary', help_text='Tailwind class e.g. text-blue-500', max_length=100),
        ),
    ]
